# Generated by Django 3.2 on 2025-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('duong_dan', models.SlugField(unique=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hinh_anh', models.ImageField(upload_to='san_pham/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
